/* Generated By:JJTree: Do not edit this line. BSHFormalComment.java */
using System;
namespace bsh
{
	
	[Serializable]
	public class BSHFormalComment:SimpleNode
	{
		public System.String text;
		
		public BSHFormalComment(int id):base(id)
		{
		}
	}
}