/// <summary>**************************************************************************
/// *
/// This file is part of the BeanShell Java Scripting distribution.          *
/// Documentation and updates may be found at http://www.beanshell.org/      *
/// *
/// Sun Public License Notice:                                               *
/// *
/// The contents of this file are subject to the Sun Public License Version  *
/// 1.0 (the "License"); you may not use this file except in compliance with *
/// the License. A copy of the License is available at http://www.sun.com    * 
/// *
/// The Original Code is BeanShell. The Initial Developer of the Original    *
/// Code is Pat Niemeyer. Portions created by Pat Niemeyer are Copyright     *
/// (C) 2000.  All Rights Reserved.                                          *
/// *
/// GNU Public License Notice:                                               *
/// *
/// Alternatively, the contents of this file may be used under the terms of  *
/// the GNU Lesser General Public License (the "LGPL"), in which case the    *
/// provisions of LGPL are applicable instead of those above. If you wish to *
/// allow use of your version of this file only under the  terms of the LGPL *
/// and not to allow others to use your version of this file under the SPL,  *
/// indicate your decision by deleting the provisions above and replace      *
/// them with the notice and other provisions required by the LGPL.  If you  *
/// do not delete the provisions above, a recipient may use your version of  *
/// this file under either the SPL or the LGPL.                              *
/// *
/// Patrick Niemeyer (pat@pat.net)                                           *
/// Author of Learning Java, O'Reilly & Associates                           *
/// http://www.pat.net/~pat/                                                 *
/// *
/// ***************************************************************************
/// </summary>
using System;
namespace bsh
{
	
	[Serializable]
	class BSHTryStatement:SimpleNode
	{
		internal BSHTryStatement(int id):base(id)
		{
		}
		
		public override System.Object eval(CallStack callstack, Interpreter interpreter)
		{
			BSHBlock tryBlock = ((BSHBlock) jjtGetChild(0));
			
			System.Collections.ArrayList catchParams = System.Collections.ArrayList.Synchronized(new System.Collections.ArrayList(10));
			System.Collections.ArrayList catchBlocks = System.Collections.ArrayList.Synchronized(new System.Collections.ArrayList(10));
			
			int nchild = jjtGetNumChildren();
			Node node = null;
			int i = 1;
			while ((i < nchild) && ((node = jjtGetChild(i++)) is BSHFormalParameter))
			{
				catchParams.Add(node);
				catchBlocks.Add(jjtGetChild(i++));
				node = null;
			}
			// finaly block
			BSHBlock finallyBlock = null;
			if (node != null)
				finallyBlock = (BSHBlock) node;
			
			// Why both of these?
			
			TargetError target = null;
			//UPGRADE_NOTE: Exception 'java.lang.Throwable' was converted to 'System.Exception' which has different behavior. "ms-help://MS.VSCC.v80/dv_commoner/local/redirect.htm?index='!DefaultContextWindowIndex'&keyword='jlca1100'"
			System.Exception thrown = null;
			System.Object ret = null;
			
			/*
			Evaluate the contents of the try { } block and catch any resulting
			TargetErrors generated by the script.
			We save the callstack depth and if an exception is thrown we pop
			back to that depth before contiuing.  The exception short circuited
			any intervening method context pops.
			
			Note: we the stack info... what do we do with it?  append
			to exception message?
			*/
			int callstackDepth = callstack.depth();
			try
			{
				ret = tryBlock.eval(callstack, interpreter);
			}
			catch (TargetError e)
			{
				target = e;
				System.String stackInfo = "Bsh Stack: ";
				while (callstack.depth() > callstackDepth)
				{
					stackInfo += ("\t" + callstack.pop() + "\n");
				}
			}
			
			// unwrap the target error
			if (target != null)
				thrown = target.Target;
			
			
			// If we have an exception, find a catch
			if (thrown != null)
			{
				int n = catchParams.Count;
				for (i = 0; i < n; i++)
				{
					// Get catch block
					BSHFormalParameter fp = (BSHFormalParameter) catchParams[i];
					
					// Should cache this subject to classloader change message
					// Evaluation of the formal parameter simply resolves its
					// type via the specified namespace.. it doesn't modify the
					// namespace.
					fp.eval(callstack, interpreter);
					
					if (fp.type == null && interpreter.StrictJava)
						throw new EvalError("(Strict Java) Untyped catch block", this, callstack);
					
					// If the param is typed check assignability
					if (fp.type != null)
						try
						{
							//UPGRADE_NOTE: Exception 'java.lang.Throwable' was converted to 'System.Exception' which has different behavior. "ms-help://MS.VSCC.v80/dv_commoner/local/redirect.htm?index='!DefaultContextWindowIndex'&keyword='jlca1100'"
							thrown = (System.Exception) Types.castObject(thrown, fp.type, Types.ASSIGNMENT);
						}
						catch (UtilEvalError e)
						{
							/*
							Catch the mismatch and continue to try the next
							Note: this is innefficient, should have an
							isAssignableFrom() that doesn't throw
							// TODO: we do now have a way to test assignment
							// 	in castObject(), use it?
							*/
							continue;
						}
					
					// Found match, execute catch block
					BSHBlock cb = (BSHBlock) (catchBlocks[i]);
					
					// Prepare to execute the block.
					// We must create a new BlockNameSpace to hold the catch
					// parameter and swap it on the stack after initializing it.
					
					NameSpace enclosingNameSpace = callstack.top();
					BlockNameSpace cbNameSpace = new BlockNameSpace(enclosingNameSpace);
					
					try
					{
						if (fp.type == BSHFormalParameter.UNTYPED)
						// set an untyped variable directly in the block
							cbNameSpace.setBlockVariable(fp.name, thrown);
						else
						{
							// set a typed variable (directly in the block)
							Modifiers modifiers = new Modifiers();
							cbNameSpace.setTypedVariable(fp.name, fp.type, thrown, new Modifiers());
						}
					}
					catch (UtilEvalError e)
					{
						throw new InterpreterError("Unable to set var in catch block namespace.");
					}
					
					// put cbNameSpace on the top of the stack
					callstack.swap(cbNameSpace);
					try
					{
						ret = cb.eval(callstack, interpreter);
					}
					finally
					{
						// put it back
						callstack.swap(enclosingNameSpace);
					}
					
					target = null; // handled target
					break;
				}
			}
			
			// evaluate finally block
			if (finallyBlock != null)
				ret = finallyBlock.eval(callstack, interpreter);
			
			// exception fell through, throw it upward...
			if (target != null)
				throw target;
			
			if (ret is ReturnControl)
				return ret;
			else
				return Primitive.VOID;
		}
	}
}