/* Generated By:JJTree: Do not edit this line. src/bsh\ParserTreeConstants.java */
using System;
namespace bsh
{
	
	public struct ParserTreeConstants_Fields{
		public readonly static int JJTVOID = 0;
		public readonly static int JJTCLASSDECLARATION = 1;
		public readonly static int JJTMETHODDECLARATION = 2;
		public readonly static int JJTPACKAGEDECLARATION = 3;
		public readonly static int JJTIMPORTDECLARATION = 4;
		public readonly static int JJTVARIABLEDECLARATOR = 5;
		public readonly static int JJTARRAYINITIALIZER = 6;
		public readonly static int JJTFORMALPARAMETERS = 7;
		public readonly static int JJTFORMALPARAMETER = 8;
		public readonly static int JJTTYPE = 9;
		public readonly static int JJTRETURNTYPE = 10;
		public readonly static int JJTPRIMITIVETYPE = 11;
		public readonly static int JJTAMBIGUOUSNAME = 12;
		public readonly static int JJTASSIGNMENT = 13;
		public readonly static int JJTTERNARYEXPRESSION = 14;
		public readonly static int JJTBINARYEXPRESSION = 15;
		public readonly static int JJTUNARYEXPRESSION = 16;
		public readonly static int JJTCASTEXPRESSION = 17;
		public readonly static int JJTPRIMARYEXPRESSION = 18;
		public readonly static int JJTMETHODINVOCATION = 19;
		public readonly static int JJTPRIMARYSUFFIX = 20;
		public readonly static int JJTLITERAL = 21;
		public readonly static int JJTARGUMENTS = 22;
		public readonly static int JJTALLOCATIONEXPRESSION = 23;
		public readonly static int JJTARRAYDIMENSIONS = 24;
		public readonly static int JJTBLOCK = 25;
		public readonly static int JJTFORMALCOMMENT = 26;
		public readonly static int JJTSWITCHSTATEMENT = 27;
		public readonly static int JJTSWITCHLABEL = 28;
		public readonly static int JJTIFSTATEMENT = 29;
		public readonly static int JJTWHILESTATEMENT = 30;
		public readonly static int JJTFORSTATEMENT = 31;
		public readonly static int JJTENHANCEDFORSTATEMENT = 32;
		public readonly static int JJTTYPEDVARIABLEDECLARATION = 33;
		public readonly static int JJTSTATEMENTEXPRESSIONLIST = 34;
		public readonly static int JJTRETURNSTATEMENT = 35;
		public readonly static int JJTTHROWSTATEMENT = 36;
		public readonly static int JJTTRYSTATEMENT = 37;
		public readonly static System.String[] jjtNodeName = new System.String[]{"void", "ClassDeclaration", "MethodDeclaration", "PackageDeclaration", "ImportDeclaration", "VariableDeclarator", "ArrayInitializer", "FormalParameters", "FormalParameter", "Type", "ReturnType", "PrimitiveType", "AmbiguousName", "Assignment", "TernaryExpression", "BinaryExpression", "UnaryExpression", "CastExpression", "PrimaryExpression", "MethodInvocation", "PrimarySuffix", "Literal", "Arguments", "AllocationExpression", "ArrayDimensions", "Block", "FormalComment", "SwitchStatement", "SwitchLabel", "IfStatement", "WhileStatement", "ForStatement", "EnhancedForStatement", "TypedVariableDeclaration", "StatementExpressionList", "ReturnStatement", "ThrowStatement", "TryStatement"};
	}
	public interface ParserTreeConstants
	{
		//UPGRADE_NOTE: Members of interface 'ParserTreeConstants' were extracted into structure 'ParserTreeConstants_Fields'. "ms-help://MS.VSCC.v80/dv_commoner/local/redirect.htm?index='!DefaultContextWindowIndex'&keyword='jlca1045'"
		
		
	}
}